# See https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "join"
version = "2.0.0"
edition = "2021"
authors = ["Nick Dower <nicholasdower@gmail.com>"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
atty = "0.2"
